"""
This is a setup.py script generated by py2app

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP_NAME = "HackerNewsMenuBar"
APP = ['hn_menu_bar.py']
DATA_FILES = [] # No extra data files needed for this simple app
OPTIONS = {
    'argv_emulation': False, # Disabled due to Carbon framework error on modern macOS
    'iconfile': 'icon.icns', # Use icon.icns from the project directory
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Hacker News Menu Bar",
        'CFBundleIdentifier': "com.darkolorin.hackernewsmenubar", # IMPORTANT: Change this to something unique if you plan to distribute!
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2025 Alexey Moiseenkov. All rights reserved.", # Optional: Update
        'LSUIElement': True,  # Re-enable LSUIElement for background-only behavior
    },
    'packages': ['requests', 'rumps'], # Ensure necessary packages are included
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
) 